name: Bug report
description: Create a bug report to help us improve
title: '[BUG] '
labels: ['BUG']
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Is this a bug in this module?
      options:
        - label: Make sure you have updated to the latest version of the module
          required: true
        - label: Is there an existing issue for this?
          required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. Screenshots are always helpful to understand the problem.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS:
        - Browser:
        - Companion Version:
        - Module Version:
        - StageTime Version:
  - type: textarea
    id: context
    attributes:
      label: Additional context
