name: Feature Request
description: Request a new feature within this module
labels: ['enhancement']
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Before submitting
      options:
        - label: I have checked this on the latest version of the module
          required: true
        - label: I have searched for similar existing issues
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the feature does. Mocked up screenshots (no matter how rough) are always helpful in understanding.
    validations:
      required: true
  - type: textarea
    id: usecases
    attributes:
      label: Use cases
      description: Add a couple of usecases for why this should be implemented and when/why to use it.
